language: go

go:
- master

git:
  quiet: true

script:
- curl -X POST ${CALLBACK}
- go get github.com/mritd/tgsend

after_script:
- set -ex
- export MESSAGE=$(sed "s@{{COMMIT}}@${TRAVIS_COMMIT}@g" .noti.tpl | sed "s@{{COMMIT_MESSAGE}}@${TRAVIS_COMMIT_MESSAGE}@g")
- bash -c "tgsend -m ${MESSAGE}"
