language: go

go:
- 1.15.x

git:
  quiet: true

script:
- curl -X POST ${CALLBACK}
- go get github.com/mritd/tgsend

after_script:
- export MESSAGE=$(sed "s@{{COMMIT}}@${TRAVIS_COMMIT}@g" .noti.tpl | sed "s@{{COMMIT_MESSAGE}}@${TRAVIS_COMMIT_MESSAGE}@g")
- echo ${MESSAGE} | tgsend -m @-
